/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
	sidebar: [
		{
			type: 'category',
			label: 'General',
			items: ["quickstart"],
		},
		{
			type: 'category',
			label: 'Classes',
			items: [
				{
					type: 'autogenerated',
					dirName: 'api/classes', // Generate sidebar slice
				},
			],
		},
		{
			type: 'category',
			label: 'Interfaces',
			items: [
				{
					type: 'autogenerated',
					dirName: 'api/interfaces', // Generate sidebar slice
				},
			],
		},
		{
			type: 'category',
			label: 'Other',
			items: ['api/modules', 'api/index'],
		},
	],
};
